# Generated by Django 4.1.3 on 2023-01-09 15:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields


class Migration(migrations.Migration):

    initial = False

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill_Level',
            fields=[
                ('Skill_Level_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Skill_Name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('[+-/%]', inverse_match=True)])),
                ('Skill_Description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('UsersID', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=12, unique=True)),
                ('Password', django_cryptography.fields.encrypt(models.CharField(max_length=15))),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('EmployeesID', models.OneToOneField(db_column='EmployeesID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='project.users')),
                ('First_Name', models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator('[+-/%]', inverse_match=True)])),
                ('Last_Name', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator('[+-/%]', inverse_match=True)])),
                ('DOB', models.DateField()),
                ('Email', models.EmailField(max_length=50, unique=True)),
                ('Skill_Level', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('[+-/%]', inverse_match=True)])),
                ('Active', models.BooleanField(default=False)),
                ('Age', models.IntegerField()),
            ],
        ),
    ]
