# Generated by Django 4.1.3 on 2023-01-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Password',
            field=models.CharField(max_length=15),
        ),
    ]
