# Generated by Django 4.1.3 on 2023-01-16 09:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_employees_first_name_alter_employees_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Password',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('[+-/%=]', inverse_match=True)]),
        ),
        migrations.AlterField(
            model_name='users',
            name='Username',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator('[+-/%=]', inverse_match=True)]),
        ),
    ]
