# Generated by Django 4.1.3 on 2023-01-16 13:56

import django.core.validators
from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_alter_users_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Password',
            field=encrypted_model_fields.fields.EncryptedCharField(validators=[django.core.validators.RegexValidator('[+-/%=]', inverse_match=True)]),
        ),
    ]
