# Generated by Django 4.1.3 on 2023-01-30 09:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_alter_users_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='Skill_Level',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='project.skill_level', validators=[django.core.validators.RegexValidator('[+-/%=]', inverse_match=True)]),
        ),
    ]
