# Generated by Django 4.1.3 on 2023-01-30 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_alter_employees_skill_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='Skill_Level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.skill_level'),
        ),
    ]
