# Generated by Django 4.1.3 on 2023-01-30 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_alter_employees_skill_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='Skill_Level',
        ),
        migrations.AddField(
            model_name='employees',
            name='Skill_Level_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Skill_Level', to='project.skill_level'),
            preserve_default=False,
        ),
    ]
