# Generated by Django 4.1.3 on 2023-01-30 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_remove_employees_skill_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='Skill_Level_ID',
        ),
        migrations.AddField(
            model_name='employees',
            name='Skill_Level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Skill_Level', to='project.skill_level'),
        ),
    ]
